version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    ports:
      - 8000:8000
      - 40010:40010

