basePath: /
definitions:
  api.JSONError:
    properties:
      error:
        type: string
    type: object
  handler.LastTradedPriceResponse:
    properties:
      ltp:
        items:
          $ref: '#/definitions/handler.PairLTP'
        type: array
    type: object
  handler.PairLTP:
    properties:
      amount:
        type: string
      pair:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API for retrieval of the Last Traded Price of Bitcoin
  title: Last Traded Price API
  version: "1.0"
paths:
  /api/v1/ltp:
    get:
      consumes:
      - application/json
      description: Get the last traded price of a pair from Kraken api
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LastTradedPriceResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/api.JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.JSONError'
      summary: Get Last Traded Price
      tags:
      - Kraken
swagger: "2.0"
